In [2]:
import pandas as pd
import numpy as np

Vector and matrices

In [3]:
from numpy import array 
m = array([[1,2,3] , [3,2,1]])
m

array([[1, 2, 3],
       [3, 2, 1]])

In [4]:
# addition
A = array([[1,2,3] , [2,3,4]])
B = array([[2,3,4], [2,1,3]])
print(A+B)

[[3 5 7]
 [4 4 7]]


In [5]:
# subtraction
A-B

array([[-1, -1, -1],
       [ 0,  2,  1]])

In [6]:
# multiplication
(A*B)

array([[ 2,  6, 12],
       [ 4,  3, 12]])

In [7]:
# division
(A/B)

array([[0.5       , 0.66666667, 0.75      ],
       [1.        , 3.        , 1.33333333]])

In [9]:
from numpy import *
a = array([['mon' , 13 ,21,13,14],
           [ 'tue' , 12, 32, 4 ,5],
           [ 'wed' , 21,45,6,3],
           ['thu' , 2,4,5,6 ],
           ['fri', 3,1,2,4],
           [ 'sat', 2,4,2,5],
           [ 'sun' , 3,5,6,7]])
a

array([['mon', '13', '21', '13', '14'],
       ['tue', '12', '32', '4', '5'],
       ['wed', '21', '45', '6', '3'],
       ['thu', '2', '4', '5', '6'],
       ['fri', '3', '1', '2', '4'],
       ['sat', '2', '4', '2', '5'],
       ['sun', '3', '5', '6', '7']], dtype='<U11')

In [11]:
# data for thuresday
print(a[3])

['thu' '2' '4' '5' '6']


In [12]:
# data for 3 row and 4 col
print(a[3,4])

6


In [19]:
from numpy import *
a = array([['mon' , 13 ,21,13,14],
           [ 'tue', 12, 32, 4 ,5],
           [ 'wed' , 21,45,6,3],
           ['thu' , 2,4,5,6 ],
           ['fri', 3,1,2,4],
           [ 'sat', 2,4,2,5],
           [ 'sun', 3,5,6,7]])
new = append(a, [['avg', 4,3,2,1]],0)
print(new)

[['mon' '13' '21' '13' '14']
 ['tue' '12' '32' '4' '5']
 ['wed' '21' '45' '6' '3']
 ['thu' '2' '4' '5' '6']
 ['fri' '3' '1' '2' '4']
 ['sat' '2' '4' '2' '5']
 ['sun' '3' '5' '6' '7']
 ['avg' '4' '3' '2' '1']]


In [29]:
new1 = insert(new,[3],[[1],[3],[7],[2],[3],[4],[5],[3]],1)

In [30]:
print(new1)

[['mon' '13' '21' '1' '13' '14']
 ['tue' '12' '32' '3' '4' '5']
 ['wed' '21' '45' '7' '6' '3']
 ['thu' '2' '4' '2' '5' '6']
 ['fri' '3' '1' '3' '2' '4']
 ['sat' '2' '4' '4' '2' '5']
 ['sun' '3' '5' '5' '6' '7']
 ['avg' '4' '3' '3' '2' '1']]
